version: '3'

services:
  angular-dev:
    container_name: angular_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: angfe:dev
    ports:
      - "4400:4200"
    volumes:
      - /app/node_modules
      - .:/app

